// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzw7HgG3JEd9UZz99G3tuYSOyqPWc2LGs',
    appId: '1:996622189595:web:c0f2c90db923b750aea4be',
    messagingSenderId: '996622189595',
    projectId: 'tic-tac-toe-15a9c',
    authDomain: 'tic-tac-toe-15a9c.firebaseapp.com',
    storageBucket: 'tic-tac-toe-15a9c.appspot.com',
    measurementId: 'G-WS5W5JH1DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1rmy_xnY3N8lGcv8iQysbh-Nh8tsudWw',
    appId: '1:996622189595:android:78e7f2db85c32fedaea4be',
    messagingSenderId: '996622189595',
    projectId: 'tic-tac-toe-15a9c',
    storageBucket: 'tic-tac-toe-15a9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_a5CrAkzaE5I0OMz3wXl0-RboykWO05c',
    appId: '1:996622189595:ios:c60ab1da60b5b2efaea4be',
    messagingSenderId: '996622189595',
    projectId: 'tic-tac-toe-15a9c',
    storageBucket: 'tic-tac-toe-15a9c.appspot.com',
    iosBundleId: 'com.fdevshashanksahu.tictic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_a5CrAkzaE5I0OMz3wXl0-RboykWO05c',
    appId: '1:996622189595:ios:c7af7fa75dbf26eaaea4be',
    messagingSenderId: '996622189595',
    projectId: 'tic-tac-toe-15a9c',
    storageBucket: 'tic-tac-toe-15a9c.appspot.com',
    iosBundleId: 'com.fdevshashanksahu.tictic.RunnerTests',
  );
}
